<a href="https://colab.research.google.com/github/FranItu/CODOJOTRACK1/blob/main/Week6/HouseSales_Francisco_Iturralde.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#SEMANA 6 TAREA 2: HOUSE SALES

##Header

Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import sklearn.metrics as skmt
from sklearn.tree import DecisionTreeClassifier

In [3]:
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier

Database import

In [4]:
df = pd.read_csv('/content/drive/My Drive/Coding_Dojo/Bases_De_Datos/kc_house_data.csv')
df.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [5]:
df2 = df
df2.pop('id')
df2.pop('date')
df2.corr()

price  bedrooms  ...  sqft_living15  sqft_lot15
price          1.000000  0.308350  ...       0.585379    0.082447
bedrooms       0.308350  1.000000  ...       0.391638    0.029244
bathrooms      0.525138  0.515884  ...       0.568634    0.087175
sqft_living    0.702035  0.576671  ...       0.756420    0.183286
sqft_lot       0.089661  0.031703  ...       0.144608    0.718557
floors         0.256794  0.175429  ...       0.279885   -0.011269
waterfront     0.266369 -0.006582  ...       0.086463    0.030703
view           0.397293  0.079532  ...       0.280439    0.072575
condition      0.036362  0.028472  ...      -0.092824   -0.003406
grade          0.667434  0.356967  ...       0.713202    0.119248
sqft_above     0.605567  0.477600  ...       0.731870    0.194050
sqft_basement  0.323816  0.303093  ...       0.200355    0.017276
yr_built       0.054012  0.154178  ...       0.326229    0.070958
yr_renovated   0.126434  0.018841  ...      -0.002673    0.007854
zipcode       -0.053203 -0.152668  ...      -0.279033   -0.147221
lat            0.307003 -0.008931  ...       0.048858   -0.086419
long           0.021626  0.129473  ...       0.334605    0.254451
sqft_living15  0.585379  0.391638  ...       1.000000    0.183192
sqft_lot15     0.082447  0.029244  ...       0.183192    1.000000

[19 rows x 19 columns]

##Single Tree

In [6]:
X = df2.loc[:, ['bathrooms', 
               'sqft_living',
               'sqft_above',
               'sqft_living15']]

In [7]:
X.shape

(21613, 4)

In [8]:
y = df2.loc[:, 'price'].values

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8)

In [10]:
clf = DecisionTreeClassifier(max_depth = None, 
                             random_state = 0)

In [11]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [12]:
clf.predict(X_test)

array([225000., 369160., 162500., ..., 267000., 700000., 780000.])

In [13]:
y_test

array([302100., 289500., 264000., ..., 265000., 577500., 267500.])

In [14]:
clf.score(X_train, y_train)

0.9250433776749566

In [15]:
clf.score(X_test, y_test)

0.006476983576220218

## Bagging + Forest

In [16]:
clf = RandomForestClassifier(n_estimators=3,
                             bootstrap=True,
                             oob_score=True)

In [17]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_forest.py:564: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  UserWarning,


RandomForestClassifier(n_estimators=3, oob_score=True)

In [18]:
clf.predict(X_test)

array([225000., 286000., 345000., ..., 760500., 380000., 380000.])

In [19]:
clf.score(X_train, y_train)

0.721283979178716

In [20]:
clf.score(X_test, y_test)

0.004626416840157298

## Respuestas

**¿Cuáles son las características más importantes de tu modelo?**

Las caracteristicas mas importantes de este modelo son:
- 'bathrooms', que es el número de baños.
- 'sqft_living', que es el area de vivienda.
- 'sqft_above', que es el area de vivienda no suberranea.
- 'sqft_living15', que es el area promedio de vivienda de las 15 casas mas cercanas.

**¿Qué otros parámetros podrías haber intentado ajustar?**

Otros parametros que se pudieron haber ajustado son:
- 'Range', En este caso no se utilizo porque no habia explicacion en la base de datos de la variable. 
- 'lat', 'sqft_basement', 'bedrooms' y 'view'; que tienen correlacion alta, pero menor a 0.5